"""empty message

Revision ID: e9dae3ac286a
Revises: 7d70082c1e13
Create Date: 2020-04-19 14:09:20.897829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9dae3ac286a'
down_revision = '7d70082c1e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'created_by')
    # ### end Alembic commands ###
